name: spring-liquibase

services:
  db:
    container_name: spring-liquibase-db
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
